name: Execute remote SSH commands using password
on: [push, workflow_dispatch]
uses: appleboy/ssh-action@v1
with:
    host: ${{ secrets.HOST }}
    username: ${{ vars.USERNAME }}
    key: ${{ secrets.SSH_KEY }}
    port: 22
    script: whoami
