name: Hello World
on:
  - push
jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name:  checkout
        uses: actions/checkout@v4
      - run: |
           date > generated.txt

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.ORA1_SERV}}
          username: ubuntu
          key: ${{ vars.SSH_KEY }}
          # port: ${{ secrets.PORT }}
          script: whoami
  
