name: Hello World
on:
  - push
jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.ORA1_SERV}}
          username: ubuntu
          key: ${{ vars.SSH_KEY }}
          # port: ${{ secrets.PORT }}
          script: whoami
  
